In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_excel(
    "../data/raw/customer_churn.xlsx"
)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes

In [5]:
df.shape

(7043, 23)

In [6]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'numAdminTickets',
 'numTechTickets',
 'Churn']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  numAdminTickets   7043 non-null   int64
 21  numTechTickets    7043 non-null   int64
 22  Churn             7043 non-null   str
dtypes: float64(1), int64(4), object(1), str(17)
memory usage: 1.2+ MB

In [8]:
#check for missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
numAdminTickets     0
numTechTickets      0
Churn               0
dtype: int64

In [9]:
#check for duplicate customers
df.duplicated().sum()

np.int64(0)

In [10]:
#totalcharges is shown as object. should be number
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  numAdminTickets   7043 non-null   int64
 21  numTechTickets    7043 non-null   int64
 22  Churn             7043 non-null   str
dtypes: float64(2), int64(4), str(17)
memory usage: 1.2 MB

In [12]:
#fill any missing charges with median. as median is better than man value for skewed data
df['TotalCharges'] = (df['TotalCharges'].fillna(df['TotalCharges'].median()))
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes

In [13]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
numAdminTickets     0
numTechTickets      0
Churn               0
dtype: int64

In [15]:
#now standardize all categorical values. fix inconsistencies for cat values like hidden spaces,etc
categorical_vals = df.select_dtypes(include='object').columns
for col in categorical_vals:
    df[col] = df[col].str.strip()

C:\Users\User\AppData\Local\Temp\ipykernel_19984\1076994704.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_vals = df.select_dtypes(include='object').columns

In [16]:
#now adding new advanced cols
#CUSTOMER LIFETIME VALUES(CLV) = MonthlyCharges * tenure
df['customer_lifetime_value'] = (df['MonthlyCharges'] * df['tenure'])
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn,customer_lifetime_value
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No,29.85
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0,0,No,1936.30
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes,107.70
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No,1903.50
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes,141.40

In [17]:
#REVENUE TIER
conditions = [
    df['customer_lifetime_value'] < 1000,

    (df['customer_lifetime_value'] >= 1000) & (df['customer_lifetime_value'] < 3000),

    df['customer_lifetime_value'] > 3000
]

choices = ['Bronze', 'Silver', 'Gold']

df['revenue_tier'] = np.select(conditions,choices,default='Bronze')

In [18]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn,customer_lifetime_value,revenue_tier
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No,29.85,Bronze
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0,0,No,1936.30,Silver
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes,107.70,Bronze
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No,1903.50,Silver
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes,141.40,Bronze

In [19]:
#SUPPORT FRUSTRATION SCORE = tech_ticket *2 + admin_ticket
#Tech problems hurt retention more.
df['support_frustration_score'] = (df['numTechTickets'] * 2 + df['numAdminTickets'])
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn,customer_lifetime_value,revenue_tier,support_frustration_score
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No,29.85,Bronze,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0,0,No,1936.30,Silver,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes,107.70,Bronze,0
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No,1903.50,Silver,6
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes,141.40,Bronze,0

In [20]:
#SERVICE ADOPTION SCORE = More service usage = lower churn
service_columns = [
    "PhoneService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies"
]

#convert yes -> 1
for col in service_columns :
    df[col] = np.where(
        df[col] == 'Yes',
        1,
        0
    )

#create score 
df['service_adoption_score'] = (
    df[service_columns].sum(axis=1)
)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn,customer_lifetime_value,revenue_tier,support_frustration_score,service_adoption_score
0,7590-VHVEG,Female,0,Yes,No,1,0,No phone service,DSL,0,1,0,0,0,0,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No,29.85,Bronze,0,1
1,5575-GNVDE,Male,0,No,No,34,1,No,DSL,1,0,1,0,0,0,One year,No,Mailed check,56.95,1889.50,0,0,No,1936.30,Silver,0,3
2,3668-QPYBK,Male,0,No,No,2,1,No,DSL,1,1,0,0,0,0,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes,107.70,Bronze,0,3
3,7795-CFOCW,Male,0,No,No,45,0,No phone service,DSL,1,0,1,1,0,0,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No,1903.50,Silver,6,3
4,9237-HQITU,Female,0,No,No,2,1,No,Fiber optic,0,0,0,0,0,0,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes,141.40,Bronze,0,1

In [21]:
#BILLING RISK SCORE  = Risk indicators:Month-to-month contract,Electronic check,Paperless billing
#higher score = higher churn
df['billing_risk_score'] = 0

df.loc[
    df['Contract'] == 'Month-to-month',
    'billing_risk_score'
] += 3

df.loc[
    df['PaymentMethod'] == 'Electronic check',
    'billing_risk_score'
] += 2

df.loc[
    df['PaperlessBilling'] == 'Yes',
    'billing_risk_score'
] +=1

In [22]:
#ENGAGEMENT SCORE = tenure + service adoption - frustration
#higher engagemnet = stickier customer

df['engagement_score'] = (
    (df['tenure'] * 0.5)
    +
    (df['service_adoption_score'] * 5)
    -
    (df['support_frustration_score'] * 2)
)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn,customer_lifetime_value,revenue_tier,support_frustration_score,service_adoption_score,billing_risk_score,engagement_score
0,7590-VHVEG,Female,0,Yes,No,1,0,No phone service,DSL,0,1,0,0,0,0,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No,29.85,Bronze,0,1,6,5.5
1,5575-GNVDE,Male,0,No,No,34,1,No,DSL,1,0,1,0,0,0,One year,No,Mailed check,56.95,1889.50,0,0,No,1936.30,Silver,0,3,0,32.0
2,3668-QPYBK,Male,0,No,No,2,1,No,DSL,1,1,0,0,0,0,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes,107.70,Bronze,0,3,4,16.0
3,7795-CFOCW,Male,0,No,No,45,0,No phone service,DSL,1,0,1,1,0,0,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No,1903.50,Silver,6,3,0,25.5
4,9237-HQITU,Female,0,No,No,2,1,No,Fiber optic,0,0,0,0,0,0,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes,141.40,Bronze,0,1,6,6.0

In [23]:
#HIGH VALUE CHURN FLAG = expensive customer we lost

df['high_value_churn_flag'] = np.where(
    (df['revenue_tier'] == 'Gold')
    &
    (df['Churn'] == 'Yes'),
    1,
    0
)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn,customer_lifetime_value,revenue_tier,support_frustration_score,service_adoption_score,billing_risk_score,engagement_score,high_value_churn_flag
0,7590-VHVEG,Female,0,Yes,No,1,0,No phone service,DSL,0,1,0,0,0,0,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No,29.85,Bronze,0,1,6,5.5,0
1,5575-GNVDE,Male,0,No,No,34,1,No,DSL,1,0,1,0,0,0,One year,No,Mailed check,56.95,1889.50,0,0,No,1936.30,Silver,0,3,0,32.0,0
2,3668-QPYBK,Male,0,No,No,2,1,No,DSL,1,1,0,0,0,0,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes,107.70,Bronze,0,3,4,16.0,0
3,7795-CFOCW,Male,0,No,No,45,0,No phone service,DSL,1,0,1,1,0,0,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No,1903.50,Silver,6,3,0,25.5,0
4,9237-HQITU,Female,0,No,No,2,1,No,Fiber optic,0,0,0,0,0,0,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes,141.40,Bronze,0,1,6,6.0,0

In [32]:
#CHURN RISK SEGMENT

risk_score = (
    df["billing_risk_score"]
    +
    df["support_frustration_score"]
)


conditions = [
    risk_score <= 3,
    (risk_score > 3)
    & (risk_score <= 6),
    risk_score > 6
]

choices = [
    "Low Risk",
    "Medium Risk",
    "High Risk"
]

df["churn_risk_segment"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn,customer_lifetime_value,revenue_tier,support_frustration_score,service_adoption_score,billing_risk_score,engagement_score,high_value_churn_flag,churn_risk_segment
0,7590-VHVEG,Female,0,Yes,No,1,0,No phone service,DSL,0,1,0,0,0,0,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No,29.85,Bronze,0,1,6,5.5,0,Medium Risk
1,5575-GNVDE,Male,0,No,No,34,1,No,DSL,1,0,1,0,0,0,One year,No,Mailed check,56.95,1889.50,0,0,No,1936.30,Silver,0,3,0,32.0,0,Low Risk
2,3668-QPYBK,Male,0,No,No,2,1,No,DSL,1,1,0,0,0,0,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes,107.70,Bronze,0,3,4,16.0,0,Medium Risk
3,7795-CFOCW,Male,0,No,No,45,0,No phone service,DSL,1,0,1,1,0,0,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No,1903.50,Silver,6,3,0,25.5,0,Medium Risk
4,9237-HQITU,Female,0,No,No,2,1,No,Fiber optic,0,0,0,0,0,0,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes,141.40,Bronze,0,1,6,6.0,0,Medium Risk

In [33]:
#validate features
df["revenue_tier"].value_counts()

revenue_tier
Bronze    2907
Gold      2202
Silver    1934
Name: count, dtype: int64

In [34]:
df["churn_risk_segment"].value_counts()

churn_risk_segment
Low Risk       3202
Medium Risk    2630
High Risk      1211
Name: count, dtype: int64

In [37]:
#save the changed and upgraded dataset
df.to_csv(
    "../data/updated/upgraded_customer_retention.csv",
    index=False
)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   str
 1   gender                     7043 non-null   str
 2   SeniorCitizen              7043 non-null   int64
 3   Partner                    7043 non-null   str
 4   Dependents                 7043 non-null   str
 5   tenure                     7043 non-null   int64
 6   PhoneService               7043 non-null   int64
 7   MultipleLines              7043 non-null   str
 8   InternetService            7043 non-null   str
 9   OnlineSecurity             7043 non-null   int64
 10  OnlineBackup               7043 non-null   int64
 11  DeviceProtection           7043 non-null   int64
 12  TechSupport                7043 non-null   int64
 13  StreamingTV                7043 non-null   int64
 14  StreamingMovies            7043 non-null   int64
 15  Contract                   7043 non-null   str
 16  PaperlessBilling           7043 non-null   str
 17  PaymentMethod              7043 non-null   str
 18  MonthlyCharges             7043 non-null   float64
 19  TotalCharges               7043 non-null   float64
 20  numAdminTickets            7043 non-null   int64
 21  numTechTickets             7043 non-null   int64
 22  Churn                      7043 non-null   str
 23  customer_lifetime_value    7043 non-null   float64
 24  revenue_tier               7043 non-null   str
 25  support_frustration_score  7043 non-null   int64
 26  service_adoption_score     7043 non-null   int64
 27  billing_risk_score         7043 non-null   int64
 28  engagement_score           7043 non-null   float64
 29  high_value_churn_flag      7043 non-null   int64
 30  churn_risk_segment         7043 non-null   str
dtypes: float64(4), int64(15), str(12)
memory usage: 1.7 MB

In [40]:
df.describe()

,SeniorCitizen,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,customer_lifetime_value,support_frustration_score,service_adoption_score,billing_risk_score,engagement_score,high_value_churn_flag
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.162147,32.371149,0.903166,0.286668,0.344881,0.343888,0.290217,0.384353,0.387903,64.761692,2281.916928,0.515689,0.419566,2279.581350,1.354820,2.941076,2.914383,28.181315,0.048985
std,0.368612,24.559481,0.295752,0.452237,0.475363,0.475038,0.453895,0.486477,0.487307,30.090047,2265.270398,1.275299,1.250117,2264.729447,2.797591,1.843899,2.176838,18.226655,0.215852
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,18.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.500000,0.000000
25%,0.000000,9.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.500000,402.225000,0.000000,0.000000,394.000000,0.000000,1.000000,1.000000,13.000000,0.000000
50%,0.000000,29.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,70.350000,1397.475000,0.000000,0.000000,1393.600000,0.000000,3.000000,3.000000,25.000000,0.000000
75%,0.000000,55.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,89.850000,3786.600000,0.000000,0.000000,3786.100000,2.000000,4.000000,5.000000,40.500000,0.000000
max,1.000000,72.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,118.750000,8684.800000,5.000000,9.000000,8550.000000,19.000000,7.000000,6.000000,71.000000,1.000000

In [ ]:
#split the existing 1D csv datasets into multiples usable and relevant tables for sql database. customerId as primary key connecting all tables
#CUSTOMER CSV
customers_df = df[
    [
        "customerID",
        "gender",
        "SeniorCitizen",
        "Partner",
        "Dependents",
        "tenure",
        "customer_lifetime_value",
        "revenue_tier",
        "engagement_score"
    ]
]

customers_df.to_csv(
    "../data/updated/customers.csv",
    index=False
)

In [42]:
#SUBSCRIPTION CSV
subscriptions_df = df[
    [
        "customerID",
        "Contract",
        "MonthlyCharges",
        "TotalCharges",
        "PaymentMethod",
        "PaperlessBilling",
        "billing_risk_score",
        "Churn",
        "churn_risk_segment"
    ]
]

subscriptions_df.to_csv(
    "../data/updated/subscriptions.csv",
    index=False
)

In [44]:
#SERVICES CSV
services_df = df[
    [
        "customerID",
        "InternetService",
        "PhoneService",
        "OnlineSecurity",
        "OnlineBackup",
        "DeviceProtection",
        "TechSupport",
        "StreamingTV",
        "StreamingMovies",
        "service_adoption_score"
    ]
]

services_df.to_csv(
    "../data/updated/services.csv",
    index=False
)

In [45]:
#support csv
support_df = df[
    [
        "customerID",
        "numAdminTickets",
        "numTechTickets",
        "support_frustration_score",
        "high_value_churn_flag"
    ]
]

support_df.to_csv(
    "../data/updated/support.csv",
    index=False
)